### ISSUE TITLE
Error while taking screenshot

### ISSUE THREAD

**Issue by vednig** [iamDyeus/KnickAI#6]
```python

Traceback (most recent call last):
  File "C:\Users\DOS Bhopal\OneDrive - vitbhopal.ac.in\Desktop\Fast Access\KnickAI\scripts\knickassistant.py", line 11, in <module>
    showmagic()
  File "C:\Users\DOS Bhopal\OneDrive - vitbhopal.ac.in\Desktop\Fast Access\KnickAI\scripts\FeatureExecution.py", line 166, in showmagic
    pywhatkit.take_screenshot(file_name="knick_screenshot")
AttributeError: module 'pywhatkit' has no attribute 'take_screenshot'
```

**Comment by iamDyeus** [comment]
I think I have fixed it for now... 
![snipped](https://user-images.githubusercontent.com/87000693/147025505-3d06afe4-1e54-452f-a867-9e452cf0ddb1.PNG)
